/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pipesex
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        setLocationRelativeTo(null);// centra el programa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonD = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        FondoPizarra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d.png"))); // NOI18N
        jButtonD.setBorderPainted(false);
        jButtonD.setContentAreaFilled(false);
        jButtonD.setFocusPainted(false);
        jButtonD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dFade.png"))); // NOI18N
        jButtonD.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        jButtonA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/a.png"))); // NOI18N
        jButtonA.setBorderPainted(false);
        jButtonA.setContentAreaFilled(false);
        jButtonA.setFocusPainted(false);
        jButtonA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aFade.png"))); // NOI18N
        jButtonA.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jButtonB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/b.png"))); // NOI18N
        jButtonB.setBorderPainted(false);
        jButtonB.setContentAreaFilled(false);
        jButtonB.setFocusPainted(false);
        jButtonB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bFade.png"))); // NOI18N
        jButtonB.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        jButtonE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/e.png"))); // NOI18N
        jButtonE.setBorderPainted(false);
        jButtonE.setContentAreaFilled(false);
        jButtonE.setFocusPainted(false);
        jButtonE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eFade.png"))); // NOI18N
        jButtonE.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        jButtonF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f.png"))); // NOI18N
        jButtonF.setBorderPainted(false);
        jButtonF.setContentAreaFilled(false);
        jButtonF.setFocusPainted(false);
        jButtonF.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fFade.png"))); // NOI18N
        jButtonF.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jButtonG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/g.png"))); // NOI18N
        jButtonG.setBorderPainted(false);
        jButtonG.setContentAreaFilled(false);
        jButtonG.setFocusPainted(false);
        jButtonG.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gFade.png"))); // NOI18N
        jButtonG.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jButtonH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/h.png"))); // NOI18N
        jButtonH.setBorderPainted(false);
        jButtonH.setContentAreaFilled(false);
        jButtonH.setFocusPainted(false);
        jButtonH.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hFade.png"))); // NOI18N
        jButtonH.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        jButtonI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/i.png"))); // NOI18N
        jButtonI.setBorderPainted(false);
        jButtonI.setContentAreaFilled(false);
        jButtonI.setFocusPainted(false);
        jButtonI.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iFade.png"))); // NOI18N
        jButtonI.setVerifyInputWhenFocusTarget(false);
        jButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        jButtonJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/j.png"))); // NOI18N
        jButtonJ.setBorderPainted(false);
        jButtonJ.setContentAreaFilled(false);
        jButtonJ.setFocusPainted(false);
        jButtonJ.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jFade.png"))); // NOI18N
        jButtonJ.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, -1, -1));

        jButtonK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/k.png"))); // NOI18N
        jButtonK.setBorderPainted(false);
        jButtonK.setContentAreaFilled(false);
        jButtonK.setFocusPainted(false);
        jButtonK.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kFade.png"))); // NOI18N
        jButtonK.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonK, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        jButtonC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/c.png"))); // NOI18N
        jButtonC.setBorderPainted(false);
        jButtonC.setContentAreaFilled(false);
        jButtonC.setFocusPainted(false);
        jButtonC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cFade.png"))); // NOI18N
        jButtonC.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        jButtonM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/m.png"))); // NOI18N
        jButtonM.setBorderPainted(false);
        jButtonM.setContentAreaFilled(false);
        jButtonM.setFocusPainted(false);
        jButtonM.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mFade.png"))); // NOI18N
        jButtonM.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        jButtonN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/n.png"))); // NOI18N
        jButtonN.setBorderPainted(false);
        jButtonN.setContentAreaFilled(false);
        jButtonN.setFocusPainted(false);
        jButtonN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nFade.png"))); // NOI18N
        jButtonN.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonN, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, -1, -1));

        jButtonO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/o.png"))); // NOI18N
        jButtonO.setBorderPainted(false);
        jButtonO.setContentAreaFilled(false);
        jButtonO.setFocusPainted(false);
        jButtonO.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oFade.png"))); // NOI18N
        jButtonO.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        jButtonL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/l.png"))); // NOI18N
        jButtonL.setBorderPainted(false);
        jButtonL.setContentAreaFilled(false);
        jButtonL.setFocusPainted(false);
        jButtonL.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lFade.png"))); // NOI18N
        jButtonL.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, -1, -1));

        jButtonQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/q.png"))); // NOI18N
        jButtonQ.setBorderPainted(false);
        jButtonQ.setContentAreaFilled(false);
        jButtonQ.setFocusPainted(false);
        jButtonQ.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/qFade.png"))); // NOI18N
        jButtonQ.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        jButtonR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/r.png"))); // NOI18N
        jButtonR.setBorderPainted(false);
        jButtonR.setContentAreaFilled(false);
        jButtonR.setFocusPainted(false);
        jButtonR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rFade.png"))); // NOI18N
        jButtonR.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        jButtonS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/s.png"))); // NOI18N
        jButtonS.setBorderPainted(false);
        jButtonS.setContentAreaFilled(false);
        jButtonS.setFocusPainted(false);
        jButtonS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sFade.png"))); // NOI18N
        jButtonS.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        jButtonT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/t.png"))); // NOI18N
        jButtonT.setBorderPainted(false);
        jButtonT.setContentAreaFilled(false);
        jButtonT.setFocusPainted(false);
        jButtonT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oFade.png"))); // NOI18N
        jButtonT.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        jButtonV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/v.png"))); // NOI18N
        jButtonV.setBorderPainted(false);
        jButtonV.setContentAreaFilled(false);
        jButtonV.setFocusPainted(false);
        jButtonV.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vFade.png"))); // NOI18N
        jButtonV.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonV, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        jButtonP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/p.png"))); // NOI18N
        jButtonP.setBorderPainted(false);
        jButtonP.setContentAreaFilled(false);
        jButtonP.setFocusPainted(false);
        jButtonP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pFade.png"))); // NOI18N
        jButtonP.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        jButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/w.png"))); // NOI18N
        jButtonW.setBorderPainted(false);
        jButtonW.setContentAreaFilled(false);
        jButtonW.setFocusPainted(false);
        jButtonW.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wFade.png"))); // NOI18N
        jButtonW.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        jButtonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        jButtonX.setBorderPainted(false);
        jButtonX.setContentAreaFilled(false);
        jButtonX.setFocusPainted(false);
        jButtonX.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xFade.png"))); // NOI18N
        jButtonX.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        jButtonY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/y.png"))); // NOI18N
        jButtonY.setBorderPainted(false);
        jButtonY.setContentAreaFilled(false);
        jButtonY.setFocusPainted(false);
        jButtonY.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yFade.png"))); // NOI18N
        jButtonY.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, -1, -1));

        jButtonZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/z.png"))); // NOI18N
        jButtonZ.setBorderPainted(false);
        jButtonZ.setContentAreaFilled(false);
        jButtonZ.setFocusPainted(false);
        jButtonZ.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/zFade.png"))); // NOI18N
        jButtonZ.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));

        jButtonU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/u.png"))); // NOI18N
        jButtonU.setBorderPainted(false);
        jButtonU.setContentAreaFilled(false);
        jButtonU.setFocusPainted(false);
        jButtonU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/uFade.png"))); // NOI18N
        jButtonU.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jButtonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, -1));

        FondoPizarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pizarra.png"))); // NOI18N
        getContentPane().add(FondoPizarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPizarra;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    // End of variables declaration//GEN-END:variables
}
